name: deploy
on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: "latest"

            - name: Build Web
              run:  echo `ls ./`

            - name: Deploy Web
              uses: peaceiris/actions-gh-pages@v3
              with:
                  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
                  EXTERNAL_REPOSITORY: Fernandoize/Fernandoize.github.io
                  PUBLISH_BRANCH: main
                  PUBLISH_DIR: ./blog/public
                  commit_message: ${{ github.event.head_commit.message }}